# Part 2a: Add Logging

Load and process patient data with BMI calculations.

**Your task:** Add logging statements to track the data processing steps.

---

## Load data

In [1]:
import pandas as pd
import logging 
from pathlib import Path
import os

# TODO: Import logging module
# TODO: Configure logging with basicConfig (level=INFO, format="%(levelname)s:%(message)s")
# Configure logging at the start of your program
log_level = os.getenv("LOG_LEVEL", "INFO").upper()
logging.basicConfig(level=getattr(logging, log_level), format="%(levelname)s:%(message)s")
# TODO: Add logging.info() statement before reading CSV

logging.info("Reading CSV: data/patient_intake.csv")
df = pd.read_csv("data/patient_intake.csv")

# TODO: Add logging.info() statement after loading (mention number of rows loaded)
logging.info("Loaded %d rows", len(df))

df.head()

INFO:Reading CSV: data/patient_intake.csv
INFO:Loaded 50 rows

  patient_id first_name last_name  weight_kg  height_cm  age sex
0       P001       Mark   Johnson       91.5        177   46   M
1       P002     Donald    Walker       80.5        164   29   M
2       P003      Nancy    Rhodes       74.3        163   47   F
3       P004     Steven    Miller       64.4        171   71   M
4       P005     Javier   Johnson       72.8        178   18   M

---

## Calculate BMI

In [2]:
# TODO: Add logging.info() statement at start of BMI calculation
logging.info("BMI calculation using patient_intake.csv")

df["height_m"] = df["height_cm"] / 100
df["bmi"] = df["weight_kg"] / (df["height_m"] ** 2)
df["bmi"] = df["bmi"].round(1)

# TODO: Add logging.info() statement after BMI calculation (mention BMI range)
logging.info("Calculated BMI range: min=%s, max%s", df["bmi"].min(), df["bmi"].max())

df[["patient_id", "weight_kg", "height_cm", "bmi"]].head()

INFO:BMI calculation using patient_intake.csv
INFO:Calculated BMI range: min=19.9, max36.1

  patient_id  weight_kg  height_cm   bmi
0       P001       91.5        177  29.2
1       P002       80.5        164  29.9
2       P003       74.3        163  28.0
3       P004       64.4        171  22.0
4       P005       72.8        178  23.0

---

## Categorize BMI

In [3]:
df["bmi_category"] = pd.cut(
    df["bmi"],
    bins=[0, 18.5, 25, 30, float("inf")],
    labels=["Underweight", "Normal", "Overweight", "Obese"],
    right=False
)

df[["patient_id", "bmi", "bmi_category"]].head()

  patient_id   bmi bmi_category
0       P001  29.2   Overweight
1       P002  29.9   Overweight
2       P003  28.0   Overweight
3       P004  22.0       Normal
4       P005  23.0       Normal

---

## Summary statistics

In [5]:
summary = df.groupby("bmi_category")["patient_id"].count()
print("\nBMI category distribution:")
print(summary)

high_risk = df[df["bmi"] > 30]
print(f"\nHigh-risk patients (BMI > 30): {len(high_risk)}")

# TODO: Add logging.info() statement summarizing processing completion
logging.info("Processing complete, Summary: 21 patients Overweight, 15 Normal, 14 Obese, and none Underweight")

/tmp/ipykernel_2032/1970131739.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summary = df.groupby("bmi_category")["patient_id"].count()
INFO:Processing complete, Summary: 21 patients Overweight, 15 Normal, 14 Obese, and none Underweight

BMI category distribution:
bmi_category
Underweight     0
Normal         15
Overweight     21
Obese          14
Name: patient_id, dtype: int64

High-risk patients (BMI > 30): 14